version: '3'

services:
  signature_service:
    build: signature_service
    container_name: signature_service
    image: kaneai/signature_service:latest
    volumes:
      - ./signature_service:/app
    ports:
      - "8001:8001"
    networks:
      - default
    env_file:
      - .env

networks:
  default:
    external:
      name:
        microservice_network

