version: '3'

services:
  base64_transform:
    build: signature_service
    container_name: transform_base64
    image: kaneai/transform_base64:latest
    volumes:
      - ./base64_transform:/app
    ports:
      - "8001:8001"
    networks:
      - default
    env_file:
      - .env

networks:
  default:
    external:
      name:
        microservice_network

