version: '3'

services:
  base64_transform:
    build: base64_transform
    container_name: transform_base64
    image: kaneai/transform_base64:latest
    volumes:
      - ./base64_transform:/app
    ports:
      - "8001:8001"
    networks:
      - default

networks:
  default:
    external:
      name:
        microservice_network

